language: java
jdk: 
 -openjdk8
addons:
  sonarcloud:
    organization: "lomels"
    token:
      secure: "a2e9a08446934c53e5327e471d389f869f087c30"

script:
  - ant build
  - sonar-scanner