language: java
jdk: 
 -openjdk8

addons:
  sonarcloud:
    organization: "lomels"
    token:
      secure: "2fc40637e019b86b9dbeb543598f365fbe8d848e"

script:
  - ant build
  - sonar-scanner
